"""
File generation utilities for creating project files.
Generates placeholder files based on project specifications.
"""
from pathlib import Path
from typing import Dict, Any


class FileGenerator:
    """Handles generation of individual project files."""
    
    @staticmethod
    def generate_backend_main(project_name: str, tech_stack: str, specs: Dict[str, Any]) -> str:
        """Generate backend main.py file."""
        apis = specs.get('apis_json', {})
        api_count = len(apis) if isinstance(apis, dict) else 0
        
        return f'''"""
{project_name} - Backend Application
Generated by AutoPilot

Tech Stack: {tech_stack}
"""
from fastapi import FastAPI

app = FastAPI(title="{project_name}")

@app.get("/")
async def root():
    return {{
        "message": "Welcome to {project_name}",
        "status": "running"
    }}

@app.get("/health")
async def health_check():
    return {{"status": "healthy"}}

# TODO: Implement {api_count} API endpoints from specifications

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
    
    @staticmethod
    def generate_backend_requirements(tech_stack: str) -> str:
        """Generate backend requirements.txt file."""
        return '''# Backend Dependencies
fastapi==0.115.0
uvicorn[standard]==0.30.6
pydantic==2.9.2
python-dotenv==1.0.1

# Database
sqlalchemy==2.0.25
alembic==1.13.1

# Add other dependencies as needed
'''
    
    @staticmethod
    def generate_frontend_readme(project_name: str, tech_stack: str) -> str:
        """Generate frontend README.md file."""
        return f'''# {project_name} - Frontend

Generated by AutoPilot

## Tech Stack
{tech_stack}

## Setup

Install dependencies:
```bash
npm install
```

Run development server:
```bash
npm run dev
```

Build for production:
```bash
npm run build
```

## Project Structure

```
frontend/
├── src/
│   ├── components/
│   ├── pages/
│   ├── services/
│   └── utils/
├── public/
└── package.json
```

## Features

TODO: Implement features from specifications

## API Integration

The frontend connects to the backend API at `http://localhost:8000`

Configure the API URL in `.env`:
```
NEXT_PUBLIC_API_URL=http://localhost:8000
```
'''
    
    @staticmethod
    def generate_database_schema(project_name: str, specs: Dict[str, Any]) -> str:
        """Generate database schema.sql file."""
        database_spec = specs.get('database_json', {})
        
        return f'''-- Database Schema for {project_name}
-- Generated by AutoPilot

-- TODO: Implement database schema from specifications
-- Database spec contains: {len(database_spec)} definitions

-- Example table structure:
-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Add your tables, indexes, and constraints here
'''
    
    @staticmethod
    def generate_project_readme(
        project_name: str, 
        tech_stack: str, 
        specs: Dict[str, Any]
    ) -> str:
        """Generate main project README.md file."""
        features = specs.get('features_json', {})
        apis = specs.get('apis_json', {})
        database = specs.get('database_json', {})
        
        feature_count = len(features) if isinstance(features, dict) else 0
        api_count = len(apis) if isinstance(apis, dict) else 0
        db_count = len(database) if isinstance(database, dict) else 0
        
        return f'''# {project_name}

Generated by AutoPilot - Excel to Code Generator

## Project Overview

**Tech Stack:** {tech_stack}

This project was automatically generated from Excel specifications:
- **Features:** {feature_count} specifications
- **APIs:** {api_count} endpoints
- **Database:** {db_count} models

## Project Structure

```
{project_name}/
├── backend/           # Backend API (FastAPI)
│   ├── main.py
│   └── requirements.txt
├── frontend/          # Frontend application
│   └── README.md
├── database/          # Database schema
│   └── schema.sql
└── README.md         # This file
```

## Getting Started

### Backend Setup

1. Navigate to backend directory:
   ```bash
   cd backend
   ```

2. Create virtual environment:
   ```bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   ```

3. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

4. Run the server:
   ```bash
   python main.py
   ```

   Backend will be available at `http://localhost:8000`

### Frontend Setup

1. Navigate to frontend directory:
   ```bash
   cd frontend
   ```

2. Install dependencies:
   ```bash
   npm install
   ```

3. Run development server:
   ```bash
   npm run dev
   ```

### Database Setup

1. Create database:
   ```bash
   createdb {project_name.lower().replace(" ", "_")}
   ```

2. Run schema:
   ```bash
   psql {project_name.lower().replace(" ", "_")} < database/schema.sql
   ```

## Features

This project includes the following features based on your specifications:

TODO: List features from Excel specifications

## API Endpoints

TODO: Document API endpoints from specifications

## Development

Generated project includes:
- Backend API with FastAPI
- Frontend application structure
- Database schema
- Development environment setup

## Next Steps

1. Review generated code
2. Customize business logic
3. Implement features from specifications
4. Add authentication and authorization
5. Configure production environment
6. Deploy to hosting platform

## Support

For issues or questions about the generated code, please refer to the AutoPilot documentation.

---

**Generated:** {project_name}  
**Tech Stack:** {tech_stack}  
**Generator:** AutoPilot v1.0
'''
    
    @staticmethod
    def generate_gitignore() -> str:
        """Generate .gitignore file."""
        return '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
ENV/

# Node
node_modules/
npm-debug.log*
.next/
out/

# Environment
.env
.env.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Database
*.sqlite
*.db
'''
